server:
  port: 8080
spring:
  config:
    import: "optional:configserver:http://localhost:8071/"
  application:
    name: accounts
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
  profiles:
    active: "qa"

build:
  version: "1.0.0"